### ISSUE TITLE
Accidental typo can cause markdown crash with levelplot

### ISSUE THREAD

**Issue by MirzaCengic** [oscarperpinan/rastervis#51]
Hi Oscar,

I noticed a strange behaviour when using levelplot with mislabeled arguments. Accidentally I passed a theme to col.regions instead of par.settings, and if normal R script is used, you just get an incorrect plot and warnings() warning. However, if the same code is embedded in markdown chunk, this causes flooding of text warnings output which completely freezes R session for me. Here is some reproducible markdown example.

`
---
title: "test"
author: "Author"
date: "February 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(raster)
library(rasterVis)

r <- raster(volcano)
levelplot(r, col.regions = RdBuTheme)
````
`

**Comment by oscarperpinan** [comment]
These `warnings` are produced by `lattice::levelplot` and, in my opinion, they are well justified because this is not a typo but a mistake using the arguments.  
If they are a problem when using Rmarkdown, you may want to silent them using an option such as `warning=FALSE`. Sorry, but I cannot give more help because I am not a regular user of Rmarkdown.
