### ISSUE TITLE
Using SpatialPointsDataFrame with level plot layer fails

### ISSUE THREAD

**Issue by GeraldCNelson** [oscarperpinan/rastervis#60]
Here's the basic data
```
r <- raster(matrix(runif(100), 10))
crs(r) <- "+proj=longlat +datum=WGS84 +no_defs"

p = c("one", "-2", "three", "four", "five")
lat = c(.2, .4, .6, .8, .9)
lon= c(.2, .4, .6, .8, .9)
df <- data.frame(x = lat, y = lon, z = p)
coordinates(df) <- ~x+y
crs(df) <- crs(r)

df.point <- SpatialPoints(cbind(lon, lat))
```

This code works.
```
levelplot(r, margin=list(draw=FALSE), scales=list(draw=FALSE), col.regions=c('white', 'gray90')) +
layer(sp.points(df.point, pch=16, col=1))
```
But I'd like to label the points. This code fails
```
levelplot(r, margin=list(draw=FALSE), scales=list(draw=FALSE), col.regions=c('white', 'gray90')) +
layer(sp.points(df, pch=16, col=1))
```

As does this one

```
levelplot(r, margin=list(draw=FALSE), scales=list(draw=FALSE), col.regions=c('white', 'gray90')) +
  layer(spplot.points(df, zcol = names(df), pch=16, col=1))
```

**Comment by oscarperpinan** [comment]
> But I'd like to label the points. This code fails
> ```
> levelplot(r, margin=list(draw=FALSE), scales=list(draw=FALSE), col.regions=c('white', 'gray90')) +
>layer(sp.points(df, pch=16, col=1))
>```
This code fails because you are using `sp.points` with `df`, which is a `data.frame`. 

You should use `sp.text` (example [here](https://gis.stackexchange.com/a/222350/19344)) or `sp.pointLabel` (example [here](https://oscarperpinan.github.io/bookvis/spatial.html#proportional) with [code](https://oscarperpinan.github.io/bookvis/spatial.html#code_proportional)).

Anyway, this question is not related to any function of `rasterVis`, so I am closing this issue. You will find lots of answers and questions related to the `sp` package in [stackoverflow](https://stackoverflow.com/questions/tagged/sp) and [GIS Stackexchange](https://gis.stackexchange.com/).
